version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"


# Enable version updates for npm
  - package-ecosystem: "npm" 
    directory: "/frontend"
    schedule:
      interval: "daily"
