version: '3'
services:
  frontend:
    image: node:16
    depends_on:
      - backend
    user: "node"
    working_dir: /home/node/frontend
    network_mode: "host"
    volumes:
      - ./frontend:/home/node/frontend:rw
    expose:
      - 3000
    command: sh -c "yarn && yarn start"
  backend: 
    image: python:3.10
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:rw
    network_mode: "host"
    depends_on: 
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis
    network_mode: "host"
    command: redis-server
