name: Backend

on:
  push:
    branches: [ development ]
    paths:
      - '/*requirements.txt'
      - '/{ordsys,backend}/**'
      - '/manage.py'
      - '/.flake8'
      - '/.github/workflows/backend.yaml'

  pull_request:
    branches: [ development ]
    paths:
      - '/*requirements.txt'
      - '/{ordsys,backend}/**'
      - '/manage.py'
      - '/.flake8'
      - '/.github/workflows/backend.yaml'

  workflow_dispatch:

jobs:
  build:
    name: Lint and test backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'dev-requirements.txt'

      - name: Install dependencies
        run: python -m pip install -r dev-requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Run tests
        run: ./manage.py test
